name: build
on:
  push:
  schedule:
    - cron: '0 6 * * 0'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        
    - name: Set env variables
      run: |
        echo "GITHUB_DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
        echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV
      
    - name: Get latest Webapp release version
      run: |
        WEBAPP_RELEASE=$(curl -sX GET "https://api.github.com/repos/netbootxyz/webapp/releases/latest" | jq -r '. | .tag_name')
        echo "WEBAPP_RELEASE=${WEBAPP_RELEASE}" >> $GITHUB_ENV
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
 
    - name: Login to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}
      
    - name: Determine version numbers
      id: version_check
      continue-on-error: true
      run: |
        VERSION_TAG=${WEBAPP_RELEASE}-nbxyz1
        echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV
        
    - name: Docker meta
      if: steps.version_check.outcome == 'success' && steps.version_check.conclusion == 'success'
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: netbootxyz/netbootxyz
        labels: |
          maintainer=antonym
          org.opencontainers.image.created=${{ env.GITHUB_DATE }}
          org.opencontainers.image.authors=netboot.xyz
          org.opencontainers.image.url=https://github.com/netbootxyz/docker-netbootxyz/packages
          org.opencontainers.image.documentation=https://netboot.xyz
          org.opencontainers.image.source=https://github.com/netbootxyz/docker-netbootxyz
          org.opencontainers.image.version=${{ env.VERSION_TAG }}
          org.opencontainers.image.revision=${{ env.GITHUB_SHA }}
          org.opencontainers.image.vendor=netboot.xyz
          org.opencontainers.image.licenses=Apache-2.0
          org.opencontainers.image.ref.name=${{ env.GITHUB_SHA }}
          org.opencontainers.image.title=netbootxyz
          org.opencontainers.image.description=netboot.xyz official docker container - Your favorite operating systems in one place. A network-based bootable operating system installer based on iPXE.
      
    - name: Build and push image
      if: steps.version_check.outcome == 'success' && steps.version_check.conclusion == 'success'
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        build-args: |
         WEBAPP_VERSION=${{ env.WEBAPP_RELEASE }} 
         VERSION=${{ env.VERSION_TAG }}
         BUILD_DATE=${{ env.GITHUB_DATE }}
        tags: |
          ghcr.io/netbootxyz/netbootxyz:latest
          ghcr.io/netbootxyz/netbootxyz:${{ github.sha }}
          ghcr.io/netbootxyz/netbootxyz:${{ env.VERSION_TAG }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Bump version and push tag
      if: steps.version_check.outcome == 'success' && steps.version_check.conclusion == 'success'
      id: tag_version
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ env.VERSION_TAG }}
        WITH_V: true
        RELEASE_BRANCHES: master
